import {test,expect} from '@playwright/test';
const base=process.env.GAMJAOJ_BASE_URL||'http://127.0.0.1:18788';
for(const width of [390,1440])test(`catalog pages filter all results and keep compact IDs usable at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:960});
 const records=Array.from({length:65},(_,index)=>({version:`generated-00000000-0000-4000-8000-${String(index).padStart(12,'0')}-r1`,title:`연습 문제 ${String(index+1).padStart(2,'0')}`,statement:'두 수의 합',sampleInput:'1 2',sampleOutput:'3',mine:index<40,shared:true,generated:true,submissionsEnabled:true,category:index%2?'자료구조':'그래프',tags:['구현'],difficulty:'EASY',solveStatus:'UNATTEMPTED'}));
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;let data=[];
  if(path==='/api/me')data={id:'pagination-user',username:'learner',nickname:'감자'};
  if(path==='/api/problems')data=records;
  return route.fulfill({json:data});
 });
 await page.goto(base);const catalog=page.getByRole('region',{name:'문제 목록',exact:true}),rows=catalog.locator('.catalog-list>li');
 const reset=catalog.getByRole('button',{name:'검색 초기화',exact:true});await expect(reset).toBeVisible();await expect(reset).toBeDisabled();
 await expect(rows).toHaveCount(10);await expect(rows.first()).toContainText('연습 문제 01');
 const firstCode=await rows.first().locator('.version').innerText(),secondCode=await rows.nth(1).locator('.version').innerText();
 expect(firstCode).toMatch(/^#[A-Z0-9]{13}$/);expect(secondCode).not.toBe(firstCode);
 await expect(rows.first().locator('.version')).toHaveAttribute('title',records[0].version);
 const pagination=catalog.getByRole('navigation',{name:'문제 목록 페이지'});
 await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(rows.first()).toContainText('연습 문제 11');
 await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(rows.first()).toContainText('연습 문제 21');
 for(let i=0;i<4;i++)await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(rows).toHaveCount(5);await expect(pagination.getByRole('button',{name:'다음',exact:true})).toBeDisabled();
 if(!await catalog.getByLabel('분야',{exact:true}).isVisible())await catalog.getByRole('button',{name:/^필터/}).click();
 await catalog.getByLabel('분야',{exact:true}).selectOption('그래프');await expect(rows).toHaveCount(10);await expect(rows.first()).toContainText('연습 문제 01');
 await expect(catalog.locator('#catalog-results')).toContainText('검색 결과 33개');await expect(reset).toBeEnabled();
 await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(rows).toHaveCount(10);await expect(rows.first()).toContainText('연습 문제 21');
 await reset.click();await expect(rows).toHaveCount(10);await expect(rows.first()).toContainText('연습 문제 01');await expect(reset).toBeDisabled();
 await catalog.getByRole('button',{name:'내가 만든 문제',exact:true}).click();await expect(catalog.locator('#catalog-results')).toContainText('40개');
 await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(rows.first()).toContainText('연습 문제 11');
 await catalog.getByRole('button',{name:'다른 사람의 문제',exact:true}).click();await expect(rows.first()).toContainText('연습 문제 41');await expect(catalog.locator('#catalog-results')).toContainText('25개');
 await catalog.getByRole('button',{name:'전체 공개 문제',exact:true}).click();await catalog.getByLabel('문제 검색').fill(firstCode);
 await expect(rows).toHaveCount(1);await expect(rows.first()).toContainText('연습 문제 01');await expect(pagination).toHaveCount(0);
 await reset.click();await catalog.getByLabel('문제 검색').fill(records[64].version);await expect(rows).toHaveCount(1);await expect(rows.first()).toContainText('연습 문제 65');
 await reset.click();await page.screenshot({path:`/tmp/gamja-catalog-pagination-${width}.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await catalog.getByLabel('문제 검색').fill(firstCode);await rows.first().getByRole('button',{name:/ 풀기$/}).click();
 await expect(page.getByLabel('풀이할 문제')).toHaveValue(records[0].version);
});
