import {test,expect} from '@playwright/test';
const base=process.env.GAMJAOJ_BASE_URL||'http://127.0.0.1:18788';
for(const width of [390,1024,1280,1440,1920])test(`catalog uses desktop space and preserves list position at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:950});
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;let data=[];
  if(path==='/api/me')data={id:'desktop-user',nickname:'감자'};
  if(path==='/api/problems')data=Array.from({length:65},(_,i)=>({version:'desktop-'+i,title:`문제 ${i+1} · 조건을 이어서 생각하기`,category:i%2?'문자열':'구현',tags:['경계 확인'],thinking:{layer:i%9+1,source:'CURATED_ESTIMATE'},shared:true,submissionsEnabled:true,solveStatus:'UNATTEMPTED'}));
  if(path==='/api/my/growth')data={layer:4,nextLayer:5,nextSolved:2,required:5,eligibleProblems:7,categories:3,evidence:[7,7,6,5,2,0,0,0,0]};
  return route.fulfill({json:data});
 });
 await page.goto(base+'/#catalog');const catalog=page.getByRole('region',{name:'문제 목록',exact:true}),list=catalog.locator('.catalog-list'),growth=catalog.getByRole('region',{name:'나의 성장 겹'});
 await expect(list.locator(':scope >li')).toHaveCount(10);await expect(growth).toContainText('4겹');
 if(width===1280)await page.getByRole('button',{name:'다크 모드로 전환'}).click();
 if(width===1920)await page.locator('.sidebar-toggle').click();
 const layout=await catalog.evaluate(n=>{const main=n.querySelector('.catalog-main').getBoundingClientRect(),rail=n.querySelector('.catalog-growth').getBoundingClientRect(),list=n.querySelector('.catalog-list').getBoundingClientRect(),rows=[...n.querySelectorAll('.catalog-list>li')].map(n=>n.getBoundingClientRect());return {mainRight:main.right,mainTop:main.top,railLeft:rail.left,railBottom:rail.bottom,listTop:list.top,listBottom:list.bottom,visible:rows.filter(r=>r.top>=list.top&&r.bottom<=Math.min(list.bottom,innerHeight)).length};});
 await page.screenshot({path:`/tmp/gamja-desktop-catalog-initial-${width}.png`,fullPage:true});
 if(width>=1200){expect(layout.mainRight).toBeLessThan(layout.railLeft);expect(layout.listTop).toBeLessThan(420);expect(layout.visible).toBeGreaterThanOrEqual(6);}else expect(layout.railBottom).toBeLessThan(layout.mainTop);
 expect(await list.evaluate(n=>n.scrollHeight<=n.clientHeight+1)).toBe(true);
 const size=catalog.getByLabel('페이지당 문제 수'),pagination=catalog.getByRole('navigation',{name:'문제 목록 페이지'});
 await size.selectOption('5');await expect(list.locator('li')).toHaveCount(5);await expect(catalog.locator('#catalog-results')).toContainText('1–5번째');await expect(pagination).toContainText('1 / 13');
 await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(list.locator('li').first()).toContainText('문제 6');
 await size.selectOption('15');await expect(list.locator('li')).toHaveCount(15);await expect(list.locator('li').first()).toContainText('문제 1 ·');await expect(pagination).toContainText('1 / 5');
 for(let i=0;i<4;i++)await pagination.getByRole('button',{name:'다음',exact:true}).click();await expect(list.locator('li')).toHaveCount(5);await expect(list.locator('li').first()).toContainText('문제 61');
 await size.selectOption('10');await expect(list.locator('li')).toHaveCount(10);await expect(pagination).toContainText('1 / 7');
 if(!await catalog.getByLabel('분야',{exact:true}).isVisible())await catalog.getByRole('button',{name:/^필터/}).click();
 await catalog.getByLabel('분야',{exact:true}).selectOption('문자열');await expect(list.locator('li').first()).toContainText('문제 2 ·');await expect(catalog.locator('#catalog-results')).toContainText('검색 결과 32개');
 await size.selectOption('5');await page.reload();await expect(size).toHaveValue('5');await expect(list.locator('li')).toHaveCount(5);
 await page.screenshot({path:`/tmp/gamja-desktop-catalog-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
