import {test,expect} from '@playwright/test';
const base=process.env.GAMJAOJ_BASE_URL||'http://127.0.0.1:18790';
for(const width of [390,1024,1440])test(`diagnostic type selection preserves scope and starts callable ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({reducedMotion:'reduce'});let session=null,starts=[];
 const banks=[{id:'algo-mix-a-v2',categories:['bfs','dp','mst','arrays-strings','dfs','backtracking','binary-search','greedy','graph','basic-data-structures'],questionCount:20},{id:'core-a-v2',categories:['implementation','arrays-strings','basic-data-structures','basic-search'],questionCount:8},{id:'exam-a-v2',examType:'A',setCount:4,categories:['exam-a-implementation','exam-a-simulation','exam-a-combinatorial-search','exam-a-state-search'],questionCount:8},{id:'exam-b-v2',examType:'B',setCount:4,categories:['exam-b-indexed-structures','exam-b-priority-order','exam-b-dynamic-queries','exam-b-combined-design'],questionCount:8}];
 await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;let data=[];if(path==='/api/auth/csrf')data={headerName:'X-CSRF',token:'test'};if(path==='/api/me')data={id:'chooser-user',nickname:'진단'};if(path==='/api/problems')data=[{version:'sum-v1',title:'합',statement:'합',submissionsEnabled:true}];if(path==='/api/diagnostics/banks')data=banks;if(path==='/api/diagnostics'){if(req.method()==='POST'){starts.push(req.postDataJSON());session={id:'exam-session',bankId:'exam-b-set-02-v2',status:'ACTIVE',items:[{id:'b-item',position:0,category:'exam-b-indexed-structures',difficulty:'CORE',status:'OPEN',attempts:0,pending:0}],current:{itemId:'b-item',problemVersion:'b-version',title:'연결 명령 문제',statement:'## 규칙\n\nID 순서를 관리해요.',examples:[{input:'[[["init"],["first"]]]',output:'-1'}],languages:[{id:'JAVA',label:'Java 8',file:'UserSolution.java',timeLimitMs:5000,memoryMb:384}],api:{template:'public class UserSolution {\n public void init() {}\n public int first() { return -1; }\n}',driver:'public class Main {}'}}};data=session;}else data=session?[session]:[];}if(path==='/api/diagnostics/exam-session')data=session;await route.fulfill({json:data});});
 await page.goto(base+'/#diagnostic');const panel=page.getByRole('region',{name:'선택 진단',exact:true});await expect(panel.getByRole('heading',{name:'A형 목표 진단',exact:true})).toBeVisible();await expect(panel.locator('.diagnostic-choice-detail')).toHaveCount(1);
 await panel.getByRole('button',{name:/핵심 혼합 알고리즘 진단 A/}).click();await panel.getByRole('checkbox',{name:/너비 우선 탐색/}).uncheck();await expect(panel.getByRole('button',{name:'선택한 18문항 시작',exact:true})).toBeEnabled();
 await panel.getByRole('button',{name:/핵심 시범 진단 A/}).click();await panel.getByRole('button',{name:/핵심 혼합 알고리즘 진단 A/}).click();await expect(panel.getByRole('checkbox',{name:/너비 우선 탐색/})).not.toBeChecked();
 await panel.getByRole('button',{name:/B형 목표 진단.*개 세트/}).click();await expect(panel.getByText('함수 구현 · Java UserSolution',{exact:true})).toBeVisible();await expect(panel.getByRole('checkbox')).toHaveCount(0);await expect(panel.locator('.diagnostic-choice-start')).toBeVisible();
 for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);const style=await panel.locator('.diagnostic-choice-detail').evaluate(n=>({border:getComputedStyle(n).borderColor,blur:getComputedStyle(n).backdropFilter,shadow:getComputedStyle(n).boxShadow}));expect(style.blur).toContain('blur');expect(style.shadow).toContain('inset');expect(style.border).toMatch(/(transparent|0\))/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`/tmp/gamja-diagnostic-chooser-${width}-${theme}.png`,fullPage:true});}
 await panel.getByRole('button',{name:'B형 목표 진단 시작',exact:true}).click();await expect.poll(()=>starts).toEqual([{bankId:'exam-b-v2'}]);await expect(panel.getByRole('heading',{name:'연결 명령 문제'})).toBeAttached();await expect(page.locator('#diagnostic-source')).toContainText('class UserSolution');await expect(panel.getByRole('combobox',{name:'진단 언어'}).locator('option')).toHaveCount(1);await expect(panel.locator('.diagnostic-workspace article')).toContainText('기본');
});
