import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
const enabled=process.env.GAMJA_DIAGNOSTIC_E2E==='1';
test('isolated real diagnostic lifecycle, process restart and Docker judging',async({page})=>{
  test.skip(!enabled,'Use scripts/test-diagnostic-e2e.sh with disposable local services');
  test.setTimeout(180000);
  const app=process.env.GAMJA_DIAGNOSTIC_APP,db=process.env.GAMJA_DIAGNOSTIC_DB;
  expect(app).toMatch(/^gamja-diagnostic-e2e-app-\d+$/);expect(db).toMatch(/^gamja-diagnostic-e2e-db-\d+$/);
  const base='http://127.0.0.1:18789',username='diag_'+Date.now(),password='Local-diagnostic-test-429!';
  const bank=JSON.parse(readFileSync('../diagnostics/core-a-v1.json','utf8'));
  const sql=q=>execFileSync('docker',['exec',db,'psql','-U','diagnostic_test','-d','diagnostic_test','-At','-c',q],{encoding:'utf8'}).trim();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base);
  await page.getByRole('button',{name:'처음 왔어요'}).click();
  await page.getByLabel('닉네임',{exact:true}).fill('진단 검증');
  await page.getByLabel('아이디',{exact:true}).fill(username);
  await page.getByLabel('비밀번호',{exact:true}).fill(password);
  await page.getByLabel('비밀번호 확인',{exact:true}).fill(password);
  await page.getByLabel('초대코드',{exact:true}).fill(process.env.INVITE_CODE);
  await page.getByRole('button',{name:'가입하기',exact:true}).click();
  await expect(page.getByText(/가입했어요/)).toBeVisible();
  await page.getByLabel('아이디',{exact:true}).fill(username);
  await page.getByLabel('비밀번호',{exact:true}).fill(password);
  await page.getByRole('button',{name:'내 연습장으로'}).click();
  await page.getByRole('button',{name:'선택 진단',exact:true}).click();
  for(const name of ['배열·문자열','기초 자료구조','기초 탐색'])await page.getByLabel(name+' · 하·중 2문항').uncheck();
  await page.getByRole('button',{name:'선택한 2문항 시작'}).click();
  await expect(page.getByRole('heading',{name:'하루 뒤의 시각'})).toBeVisible();
  await page.locator('#diagnostic-source .cm-content').fill(bank.items[0].reference);
  await page.getByRole('button',{name:'직접 실행',exact:true}).click();
  await expect(page.getByText('1번 문항 실행 결과: OK')).toBeVisible({timeout:30000});
  await expect(page.getByText(/제출 0\/5/)).toBeVisible();
  await page.getByRole('button',{name:'일시정지',exact:true}).click();
  execFileSync('docker',['restart',app],{timeout:45000});
  await expect.poll(async()=>{try{return (await page.request.get(base+'/api/auth/csrf')).status();}catch{return 0;}},{timeout:45000}).toBe(200);
  await page.reload();await page.getByRole('button',{name:'선택 진단',exact:true}).click();
  await expect(page.getByRole('button',{name:'진단 이어서 풀기'})).toBeVisible();
  await expect(page.locator('#diagnostic-source')).toContainText('t/60%24');
  await page.getByRole('button',{name:'진단 이어서 풀기'}).click();
  await page.getByRole('button',{name:/정식 제출/}).click();
  await expect(page.getByRole('heading',{name:'격자 위 명령'})).toBeVisible({timeout:30000});
  await expect(page.getByText('이전 문항: 통과')).toBeVisible();
  await page.getByRole('button',{name:'부분 판정 기록 저장'}).click();
  await expect(page.getByText('부분 결과 · 판정 기록 저장됨')).toBeVisible();
  expect(sql("SELECT count(*) FROM ai_task")).toBe('0');
  await page.locator('#diagnostic-source .cm-content').fill(bank.items[1].mutant);
  for(let n=1;n<=5;n++){
    await page.getByRole('button',{name:/정식 제출/}).click();
    if(n<5)await expect(page.getByRole('button',{name:`정식 제출 (${5-n}회 남음)`})).toBeEnabled({timeout:30000});
  }
  await expect(page.getByText(/진단을 마쳤어요/)).toBeVisible({timeout:30000});
  expect(sql("SELECT status FROM diagnostic_session")).toBe('COMPLETED');
  expect(sql("SELECT string_agg(status,',' ORDER BY position) FROM diagnostic_item")).toBe('PASSED,EXHAUSTED');
  expect(sql("SELECT count(*) FROM submission WHERE diagnostic_item_id IS NOT NULL AND run_input IS NULL")).toBe('6');
  expect(sql("SELECT count(*) FROM judge_job WHERE status<>'FINISHED'")).toBe('0');
  expect(sql("SELECT count(*) FROM judge_attempt WHERE execution_environment_json IS NOT NULL AND status='COMPLETED'")).toBe('7');
  expect(sql("SELECT count(*) FROM ai_task")).toBe('0');
  await page.getByRole('button',{name:'종합 평가 요청'}).click();
  await expect(page.getByText('종합 결과 · AI 평가 사용 설정 대기')).toBeVisible();
  await page.getByRole('button',{name:'종합 평가 요청'}).click();
  expect(sql("SELECT count(*) FROM diagnostic_evaluation")).toBe('2');
  expect(sql("SELECT count(*) FROM ai_task WHERE kind='DIAGNOSTIC' AND status='HELD_DISABLED'")).toBe('1');
  expect(sql("SELECT count(*) FROM ai_attempt")).toBe('0');
  await page.getByRole('button',{name:'일반 연습으로'}).click();
  await expect(page.getByRole('button',{name:'문제 풀기',exact:true})).toHaveAttribute('aria-pressed','true');
  expect(errors).toEqual([]);
});
