import {test,expect} from '@playwright/test';
const base=process.env.GAMJAOJ_BASE_URL||'http://127.0.0.1:18788';
for(const width of [390,1440])test(`problem history and personal activity stay separate at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});let runLists=0;
 const records=Array.from({length:51},(_,i)=>({id:`s${i}`,problemVersion:i===50?'v2':'v1',status:'FINISHED',verdict:i===50?'WA':'AC',createdAt:'2026-09-26T00:00:00Z',language:'JAVA',source:`// submission ${i}`}));
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url());let data=[];
  if(url.pathname==='/api/me')data={id:'my-test',nickname:'기록'};
  if(url.pathname==='/api/problems')data=['v1','v2'].map(version=>({version,title:`문제 ${version}`,statement:'설명',sampleInput:'1 2',sampleOutput:'3',submissionsEnabled:true}));
  if(url.pathname==='/api/submissions')data=url.searchParams.has('problemVersion')?records.filter(r=>r.problemVersion===url.searchParams.get('problemVersion')).slice(0,50):records.slice(Number(url.searchParams.get('page')||0)*50,Number(url.searchParams.get('page')||0)*50+50);
  if(url.pathname.startsWith('/api/submissions/'))data=records.find(r=>url.pathname.endsWith('/'+r.id));
  if(url.pathname==='/api/my/summary')data={submitted:51,attemptedProblems:2,solvedProblems:1};
  if(url.pathname==='/api/my/problems')data={total:2,items:['v1','v2'].map((version,i)=>({version,title:`문제 ${version}`,attempts:i?1:50,accepted:i?0:50,lastSubmitted:'2026-09-26T00:00:00Z'}))};
  if(url.pathname==='/api/runs'&&route.request().method()==='GET')runLists++;
  await route.fulfill({json:data});
 });
 await page.goto(base+'/#practice');await page.getByLabel('Main.java',{exact:true}).fill('// keep my draft');
 await page.getByRole('button',{name:'제출 기록',exact:true}).click();
 await page.getByText('최근 제출 내역',{exact:false}).click();
 await expect(page.locator('#submission-results .record-list')).not.toContainText('v2');
 await page.locator('#submission-results li button').first().click();
 await page.getByLabel('풀이할 문제').selectOption('v2');
 await expect(page.locator('#submission-heading')).toHaveCount(0);
 await page.getByText('최근 제출 내역',{exact:false}).click();
 await expect(page.locator('#submission-results .record-list')).toContainText('v2');
 await expect(page.locator('#submission-results .record-list')).not.toContainText('v1');
 await page.getByRole('button',{name:'마이페이지',exact:true}).click();
 const my=page.getByRole('region',{name:'마이페이지',exact:true});
 await expect(my.getByText('문제 v1',{exact:true})).toBeVisible();
 await expect(my.getByText('문제 v2',{exact:true})).toBeVisible();
 await my.getByRole('button',{name:'전체 제출',exact:true}).click();
 await expect(my.locator('.my-records li')).toHaveCount(50);
 await my.getByRole('button',{name:'다음',exact:true}).click();
 await expect(my.locator('.my-records li')).toHaveCount(1);
 await my.locator('.my-submission').click();await expect(my.getByLabel('제출 당시 코드')).toHaveText('// submission 50');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.screenshot({path:`/tmp/gamja-my-page-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'문제 풀기',exact:true}).click();await page.getByLabel('풀이할 문제').selectOption('v1');
 if(width===390)await page.getByRole('button',{name:'코드 작성',exact:true}).click();
 await expect(page.getByLabel('Main.java',{exact:true})).toContainText('// keep my draft');
 await expect(page.getByText('최근 실행 내역',{exact:false})).toHaveCount(0);
 expect(runLists).toBe(0);
});
